--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

-- Started on 2021-08-05 10:47:31 EAT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 205 (class 1259 OID 33923)
-- Name: fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fields (
    id integer NOT NULL,
    name character varying NOT NULL,
    size double precision NOT NULL
);


ALTER TABLE public.fields OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 33921)
-- Name: fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fields_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fields_id_seq OWNER TO postgres;

--
-- TOC entry 3296 (class 0 OID 0)
-- Dependencies: 204
-- Name: fields_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fields_id_seq OWNED BY public.fields.id;


--
-- TOC entry 203 (class 1259 OID 33912)
-- Name: inputs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inputs (
    id integer NOT NULL,
    name character varying NOT NULL,
    quantity integer NOT NULL,
    metrics character varying NOT NULL,
    type character varying
);


ALTER TABLE public.inputs OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 33910)
-- Name: inputs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inputs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.inputs_id_seq OWNER TO postgres;

--
-- TOC entry 3297 (class 0 OID 0)
-- Dependencies: 202
-- Name: inputs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inputs_id_seq OWNED BY public.inputs.id;


--
-- TOC entry 207 (class 1259 OID 33934)
-- Name: procedures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.procedures (
    id integer NOT NULL,
    name character varying,
    date timestamp without time zone NOT NULL,
    activity character varying,
    field_id integer NOT NULL,
    worker_id integer NOT NULL,
    input_id integer,
    inputs_quantity integer,
    image_link character varying
);


ALTER TABLE public.procedures OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 33932)
-- Name: procedures_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.procedures_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.procedures_id_seq OWNER TO postgres;

--
-- TOC entry 3298 (class 0 OID 0)
-- Dependencies: 206
-- Name: procedures_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.procedures_id_seq OWNED BY public.procedures.id;


--
-- TOC entry 201 (class 1259 OID 33901)
-- Name: worker; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.worker (
    id integer NOT NULL,
    name character varying,
    national_id integer,
    phone_number character varying,
    type character varying
);


ALTER TABLE public.worker OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 33899)
-- Name: worker_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.worker_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.worker_id_seq OWNER TO postgres;

--
-- TOC entry 3299 (class 0 OID 0)
-- Dependencies: 200
-- Name: worker_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.worker_id_seq OWNED BY public.worker.id;


--
-- TOC entry 3140 (class 2604 OID 33926)
-- Name: fields id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fields ALTER COLUMN id SET DEFAULT nextval('public.fields_id_seq'::regclass);


--
-- TOC entry 3139 (class 2604 OID 33915)
-- Name: inputs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inputs ALTER COLUMN id SET DEFAULT nextval('public.inputs_id_seq'::regclass);


--
-- TOC entry 3141 (class 2604 OID 33937)
-- Name: procedures id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedures ALTER COLUMN id SET DEFAULT nextval('public.procedures_id_seq'::regclass);


--
-- TOC entry 3138 (class 2604 OID 33904)
-- Name: worker id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.worker ALTER COLUMN id SET DEFAULT nextval('public.worker_id_seq'::regclass);


--
-- TOC entry 3288 (class 0 OID 33923)
-- Dependencies: 205
-- Data for Name: fields; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fields (id, name, size) FROM stdin;
3	Field 1	1.1
2	Field 1	5.6
5	Field 1	1.4
6	Field 1	1.4
7	Field 1	1.4
\.


--
-- TOC entry 3286 (class 0 OID 33912)
-- Dependencies: 203
-- Data for Name: inputs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inputs (id, name, quantity, metrics, type) FROM stdin;
1	DFG Fertilizer	10	Kg	Fertilizer
3	CBDE Fertilizer	30	Kg	\N
4	CBDE Fertilizer	30	Kg	\N
5	CBDE Fertilizer	30	Kg	\N
6	CBDE Fertilizer	30	Kg	\N
\.


--
-- TOC entry 3290 (class 0 OID 33934)
-- Dependencies: 207
-- Data for Name: procedures; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.procedures (id, name, date, activity, field_id, worker_id, input_id, inputs_quantity, image_link) FROM stdin;
3	First Input Application	2021-02-10 00:00:00	Fertilizer application	2	1	1	10	https://imagelink.com
5	Procedure 1	2021-07-28 00:00:00	Fertilizer application	2	1	1	10	https://imagelink.com
\.


--
-- TOC entry 3284 (class 0 OID 33901)
-- Dependencies: 201
-- Data for Name: worker; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.worker (id, name, national_id, phone_number, type) FROM stdin;
2	Maureen Maina	785784754	+254637658475	Casual
1	Maureen Mumbi	5648790	+2546236276373	Casual
4	Testing Procedure	\N	\N	\N
5	Bill Nyamu	785784754	+254637658475	Casual
6	Bill Nyamu	785784754	+254637658475	Casual
7	Bill Nyamu	785784754	+254637658475	Casual
8	Bill Nyamu	785784754	+254637658475	Casual
9	Bill Nyamu	785784754	+254637658475	Casual
\.


--
-- TOC entry 3300 (class 0 OID 0)
-- Dependencies: 204
-- Name: fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fields_id_seq', 7, true);


--
-- TOC entry 3301 (class 0 OID 0)
-- Dependencies: 202
-- Name: inputs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inputs_id_seq', 6, true);


--
-- TOC entry 3302 (class 0 OID 0)
-- Dependencies: 206
-- Name: procedures_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.procedures_id_seq', 7, true);


--
-- TOC entry 3303 (class 0 OID 0)
-- Dependencies: 200
-- Name: worker_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.worker_id_seq', 9, true);


--
-- TOC entry 3147 (class 2606 OID 33931)
-- Name: fields fields_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fields
    ADD CONSTRAINT fields_pkey PRIMARY KEY (id);


--
-- TOC entry 3145 (class 2606 OID 33920)
-- Name: inputs inputs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inputs
    ADD CONSTRAINT inputs_pkey PRIMARY KEY (id);


--
-- TOC entry 3149 (class 2606 OID 33942)
-- Name: procedures procedures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedures
    ADD CONSTRAINT procedures_pkey PRIMARY KEY (id);


--
-- TOC entry 3143 (class 2606 OID 33909)
-- Name: worker worker_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT worker_pkey PRIMARY KEY (id);


--
-- TOC entry 3150 (class 2606 OID 33943)
-- Name: procedures procedures_field_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedures
    ADD CONSTRAINT procedures_field_id_fkey FOREIGN KEY (field_id) REFERENCES public.fields(id) ON DELETE CASCADE;


--
-- TOC entry 3152 (class 2606 OID 33953)
-- Name: procedures procedures_input_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedures
    ADD CONSTRAINT procedures_input_id_fkey FOREIGN KEY (input_id) REFERENCES public.inputs(id) ON DELETE CASCADE;


--
-- TOC entry 3151 (class 2606 OID 33948)
-- Name: procedures procedures_worker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procedures
    ADD CONSTRAINT procedures_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.worker(id) ON DELETE CASCADE;


-- Completed on 2021-08-05 10:47:32 EAT

--
-- PostgreSQL database dump complete
--

